import { INestedRoute } from './../interfaces/route';
import { AppLayout, LayoutError } from '@layouts';
import { IRoute } from '@interfaces';
import {
  PageError404,
  LoginPage,
  DashboardPage,
  SignUpPage,
  ForgotPasswordPage,
  VerifyEmailPage,
  ResetPasswordPage,
  SystemSettingsPage,
  UserProfilePage,
  PrivacyPolicyPage,
  BannerManagementPage,
  AccountManagementPage,
  BranchManagementPage,
  CustomerCategoryPage,
  CustomerManagementPage,
  CustomerDetailPage,
  CategoryManagementPage,
  ProductManagementPage,
  OrderManagementPage,
  ChanceManagementPage,
  InvoiceManagementPage,
  OtherProductManagementPage,
  CreateOrderPage,
  OrderDetailsPage,
  InvoiceDetailsPage,
  CreateChancePage,
  ChanceDetailsPage,
  CompanyInfoPage,
  StaffManagementPage,
  CampaignManagementPage,
  VoucherManagementPage,
  CreateCampaignPage,
  CampaignDetailsPage,
  CreateVoucherPage,
  VoucherDetailsPage,
} from '@pages';
import {
  PATH_404,
  PATH_HOME,
  PATH_LOGIN,
  PATH_DASHBOARD,
  PATH_FORGOT_PASSWORD,
  PATH_SIGN_UP,
  PATH_RESET_PASSWORD,
  PATH_VERIFY_EMAIL,
  PATH_GENERAL,
  PATH_USER_PROFILE,
  PATH_POLICY,
  PATH_PAY,
  PATH_BANNER,
  PATH_SETTING,
  PATH_SUB_SETTING,
  PATH_COMPANY_INFO_SETTING,
  PATH_TIER_SETTING,
  PATH_CUSTOMER_CLASS_SETTING,
  PATH_CUSTOMER_POINT_SETTING,
  PATH_COMPANY_INFO,
  PATH_TIER,
  PATH_CUSTOMER_CLASS,
  PATH_CUSTOMER_POINT,
  PATH_SALE_PROCESS,
  PATH_SALE_PROCESS_SETTING,
  PATH_ACCOUNT_MANAGEMENT,
  PATH_ACCOUNT_MANAGEMENT_SETTING,
  PATH_BRANCH,
  PATH_CUSTOMER,
  PATH_CREATE_CUSTOMER,
  PATH_CUSTOMER_PROFILE,
  PATH_CATEGORY,
  PATH_PRODUCT,
  PATH_CATEGORY_LIST,
  PATH_ORDER,
  PATH_CHANCE,
  PATH_INVOICE,
  PATH_OTHER_PRODUCT,
  PATH_CAMPAIGN_LIST,
  PATH_ADS,
  PATH_EMAIL_MARKETING,
  PATH_SMS_MARKETING,
  PATH_VOUCHER,
  PATH_SYSTEM_THEME_SETTING,
  PATH_DEPARTMENT_MANAGEMENT_SETTING,
  PATH_DEPARTMENT_MANAGEMENT,
  PATH_SYSTEM_THEME,
  PATH_CREATE_CHANCE,
  PATH_CHANCE_DETAIL,
  PATH_CREATE_ORDER,
  PATH_ORDER_DETAIL,
  PATH_INVOICE_DETAIL,
  PATH_STAFF,
  PATH_CAMPAIGN,
  PATH_CREATE_CAMPAIGN,
  PATH_CAMPAIGN_DETAILS,
  PATH_VOUCHER_LIST,
  PATH_CREATE_VOUCHER,
  PATH_VOUCHER_DETAILS,
} from './navigation';
import { enumRole } from '@configs';

export const routes: Array<IRoute> = [
  //dashboard
  { path: PATH_DASHBOARD, page: DashboardPage, layout: AppLayout },
  { path: PATH_POLICY, page: PrivacyPolicyPage, layout: AppLayout },
  { path: PATH_USER_PROFILE, page: UserProfilePage, layout: AppLayout },
  //customer
  { path: PATH_CUSTOMER, page: CustomerManagementPage, layout: AppLayout },
  { path: PATH_CREATE_CUSTOMER, page: CustomerManagementPage, layout: AppLayout },
  { path: PATH_CUSTOMER_PROFILE, page: CustomerDetailPage, layout: AppLayout },
  //category
  { path: PATH_CATEGORY_LIST, page: CategoryManagementPage, layout: AppLayout },
  { path: PATH_PRODUCT, page: ProductManagementPage, layout: AppLayout },
  { path: PATH_OTHER_PRODUCT, page: OtherProductManagementPage, layout: AppLayout },
  //Order
  { path: PATH_ORDER, page: OrderManagementPage, layout: AppLayout },
  { path: PATH_CREATE_ORDER, page: CreateOrderPage, layout: AppLayout },
  { path: PATH_ORDER_DETAIL, page: OrderDetailsPage, layout: AppLayout },
  //Chance
  { path: PATH_CHANCE, page: ChanceManagementPage, layout: AppLayout },
  { path: PATH_CREATE_CHANCE, page: CreateChancePage, layout: AppLayout },
  { path: PATH_CHANCE_DETAIL, page: ChanceDetailsPage, layout: AppLayout },
  //Invoice
  { path: PATH_INVOICE, page: InvoiceManagementPage, layout: AppLayout },
  { path: PATH_INVOICE_DETAIL, page: InvoiceDetailsPage, layout: AppLayout },
  //marketing
  { path: PATH_BANNER, page: BannerManagementPage, layout: AppLayout },
  { path: PATH_ADS, page: BannerManagementPage, layout: AppLayout },
  { path: PATH_EMAIL_MARKETING, page: BannerManagementPage, layout: AppLayout },
  { path: PATH_SMS_MARKETING, page: BannerManagementPage, layout: AppLayout },
  //campaign
  { path: PATH_CAMPAIGN, page: CampaignManagementPage, layout: AppLayout },
  { path: PATH_CREATE_CAMPAIGN, page: CreateCampaignPage, layout: AppLayout },
  { path: PATH_CAMPAIGN_DETAILS, page: CampaignDetailsPage, layout: AppLayout },
  { path: PATH_CAMPAIGN_LIST, page: CampaignManagementPage, layout: AppLayout },
  { path: PATH_VOUCHER, page: VoucherManagementPage, layout: AppLayout },
  { path: PATH_VOUCHER_LIST, page: VoucherManagementPage, layout: AppLayout },
  { path: PATH_CREATE_VOUCHER, page: CreateVoucherPage, layout: AppLayout },
  { path: PATH_VOUCHER_DETAILS, page: VoucherDetailsPage, layout: AppLayout },
  //PAY
  { path: PATH_PAY, page: DashboardPage },
  //Branch
  { path: PATH_BRANCH, page: BranchManagementPage, layout: AppLayout, role: enumRole.S_MANAGER },
  //Staff
  { path: PATH_STAFF, page: StaffManagementPage, layout: AppLayout, role: enumRole.B_MANAGER },
  //
  { path: PATH_HOME, page: DashboardPage, layout: AppLayout },
  { path: PATH_SETTING, page: SystemSettingsPage, layout: AppLayout },
  { path: PATH_SUB_SETTING, page: SystemSettingsPage, layout: AppLayout },
  { path: PATH_404, page: PageError404, layout: LayoutError },
  { page: PageError404, layout: LayoutError },
];

export const normalRoutes = [PATH_HOME];

export const authRoutes: Array<IRoute> = [
  //auth
  { path: PATH_LOGIN, page: LoginPage, auth: true },
  { path: PATH_SIGN_UP, page: SignUpPage, auth: true },
  { path: PATH_FORGOT_PASSWORD, page: ForgotPasswordPage, auth: true },
  { path: PATH_VERIFY_EMAIL, page: VerifyEmailPage, auth: true },
  { path: PATH_RESET_PASSWORD, page: ResetPasswordPage, auth: true },
  { page: PageError404, layout: LayoutError },
];

export const settingRoutes: Array<INestedRoute> = [
  { path: PATH_SETTING, subPath: '/', page: CompanyInfoPage },
  { path: PATH_COMPANY_INFO_SETTING, subPath: PATH_COMPANY_INFO, page: CompanyInfoPage },
  { path: PATH_TIER_SETTING, subPath: PATH_TIER, page: AccountManagementPage },
  { path: PATH_CUSTOMER_CLASS_SETTING, subPath: PATH_CUSTOMER_CLASS, page: CustomerCategoryPage },
  { path: PATH_CUSTOMER_POINT_SETTING, subPath: PATH_CUSTOMER_POINT, page: AccountManagementPage },
  { path: PATH_SALE_PROCESS_SETTING, subPath: PATH_SALE_PROCESS, page: BannerManagementPage },
  {
    path: PATH_ACCOUNT_MANAGEMENT_SETTING,
    subPath: PATH_ACCOUNT_MANAGEMENT,
    page: AccountManagementPage,
  },
  {
    path: PATH_DEPARTMENT_MANAGEMENT_SETTING,
    subPath: PATH_DEPARTMENT_MANAGEMENT,
    page: AccountManagementPage,
  },
  {
    path: PATH_SYSTEM_THEME_SETTING,
    subPath: PATH_SYSTEM_THEME,
    page: AccountManagementPage,
  },
  { path: PATH_404, subPath: PATH_404, page: PageError404 },
  { page: PageError404 },
];
