export const topMostSpentCustomersData = [
  {
    totalSpent: 1291000,
    id: 9,
    phone: '0866081999',
    firstName: ' ',
    lastName: 'lastName',
    dob: '944931600000',
    gender: 'Others',
    address: 'address',
    point: 0,
    cashback: 0,
    rate: 0,
    taxCode: '12345',
    email: 'email@gmail.com',
    image: 'link',
    classifications: [
      {
        id: 1,
        name: 'Doanh nghiệp',
        desc: 'None',
      },
      {
        id: 2,
        name: 'Cá nhân',
        desc: 'None',
      },
    ],
    stores: [
      {
        id: 10,
        name: 'Cửa hàng số 1',
        address: 'Hà Nội',
        email: 'email3@gmail.com',
        phone: '0393260255',
        businessType: null,
        storeImage: null,
        privacyPolicy: null,
      },
    ],
  },
  {
    totalSpent: 1136400,
    id: 8,
    phone: '0866081999',
    firstName: ' ',
    lastName: 'lastName',
    dob: '944931600000',
    gender: 'Others',
    address: 'address',
    point: 0,
    cashback: 0,
    rate: 0,
    taxCode: '12345',
    email: 'email@gmail.com',
    image: 'link',
    classifications: [
      {
        id: 2,
        name: 'Cá nhân',
        desc: 'None',
      },
      {
        id: 1,
        name: 'Doanh nghiệp',
        desc: 'None',
      },
    ],
    stores: [
      {
        id: 10,
        name: 'Cửa hàng số 1',
        address: 'Hà Nội',
        email: 'email3@gmail.com',
        phone: '0393260255',
        businessType: null,
        storeImage: null,
        privacyPolicy: null,
      },
    ],
  },
  {
    totalSpent: 9906400,
    id: 6,
    phone: '0866081999',
    firstName: ' ',
    lastName: 'lastName',
    dob: '944931600000',
    gender: 'Others',
    address: 'address',
    point: 0,
    cashback: 0,
    rate: 0,
    taxCode: '12345',
    email: 'email@gmail.com',
    image: 'link',
    classifications: [
      {
        id: 2,
        name: 'Cá nhân',
        desc: 'None',
      },
      {
        id: 1,
        name: 'Doanh nghiệp',
        desc: 'None',
      },
    ],
    stores: [
      {
        id: 10,
        name: 'Cửa hàng số 1',
        address: 'Hà Nội',
        email: 'email3@gmail.com',
        phone: '0393260255',
        businessType: null,
        storeImage: null,
        privacyPolicy: null,
      },
    ],
  },
  {
    totalSpent: 8906400,
    id: 5,
    phone: '0866081999',
    firstName: ' ',
    lastName: 'lastName',
    dob: '944931600000',
    gender: 'Male',
    address: 'address',
    point: 0,
    cashback: 0,
    rate: 0,
    taxCode: '12345',
    email: 'email@gmail.com',
    image: 'link',
    classifications: [
      {
        id: 1,
        name: 'Doanh nghiệp',
        desc: 'None',
      },
      {
        id: 2,
        name: 'Cá nhân',
        desc: 'None',
      },
    ],
    stores: [
      {
        id: 10,
        name: 'Cửa hàng số 1',
        address: 'Hà Nội',
        email: 'email3@gmail.com',
        phone: '0393260255',
        businessType: null,
        storeImage: null,
        privacyPolicy: null,
      },
    ],
  },
  {
    totalSpent: 6906400,
    id: 4,
    phone: '0866081999',
    firstName: ' ',
    lastName: 'lastName',
    dob: '944931600000',
    gender: 'Male',
    address: 'address',
    point: 0,
    cashback: 0,
    rate: 0,
    taxCode: '12345',
    email: 'email@gmail.com',
    image: 'link',
    classifications: [],
    stores: [
      {
        id: 2,
        name: 'None',
        address: 'None',
        email: 'long@gmail.com',
        phone: '0866081990',
        businessType: 'businessType',
        storeImage: 'link',
        privacyPolicy: 'privacyPolicy',
      },
    ],
  },
];
